pdb_file_name = 'ntkrnlmp.pdb'
pdb_guid = 'ECE191A20CFF4465AE46DF96C22638451'
nt_major_version = 6
nt_minor_version = 1
nt_build_number = 7601
arch = 'X64'

[offsets]
list_blink = 8
eproc_link = 392
kproc_dtb = 40
eproc_pid = 384
eproc_name = 736
eproc_peb = 824
eproc_section_base = 624
eproc_exit_status = 1092
eproc_thread_list = 776
eproc_wow64 = 800
kthread_teb = 184
ethread_list_entry = 1064
teb_peb = 96
teb_peb_x86 = 48
